apiVersion: v1
kind: Service
metadata:
  name: conflict-detection-service
  namespace: default
spec:
  selector:
    app: conflict-detection-service
  type: ClusterIP
  ports:
    - name: conflict-detection-service
      port: 8084
      targetPort: 8084
---
