apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
spec:
  selector:
    app: booking-service
  type: ClusterIP
  ports:
    - name: booking-service
      port: {{ .Values.ports.bookingService }}
      targetPort: {{ .Values.ports.bookingService }}
---
