apiGateway:
  serviceType: LoadBalancer

imagePullSecret: ghcr-secret

storage:
  createStorageClass: true
  className: gp2
  type: gp2

replicaCount:
  apiGateway: 1
  bff: 1
  driverService: 1
  bookingService: 1
  routesService: 1
  conflictDetection: 1
  messagingService: 1
  pgadmin: 0
  redisinsight: 0
