apiGateway:
  serviceType: LoadBalancer
  loadBalancerPort: 80

imagePullSecret: ghcr-secret

storage:
  createStorageClass: true
  className: gp2
  type: gp2

replicaCount:
  apiGateway: 2
  bff: 2
  driverService: 2
  bookingService: 2
  routesService: 2
  conflictDetection: 2
  messagingService: 2
  pgadmin: 0
  redisinsight: 0
