apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: default
  labels:
    app: bff
spec:
  selector:
    matchLabels:
      app: bff
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: bff
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: bff:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: bff
---
