apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: default
spec:
  selector:
    app: bff
  type: ClusterIP
  ports:
    - name: bff
      port: {{ .Values.ports.bff }}
      targetPort: {{ .Values.ports.bff }}
---
