apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: default
spec:
  selector:
    app: pgadmin
  type: ClusterIP
  ports:
    - name: pgadmin
      port: 5050
      targetPort: 80
---
